apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: shogun-assign-taxonomy-
spec:
  entrypoint: shogun-pipeline
  #onExit: exit-hander
  volumes:
  - name: gluster-volumes-user
    glusterfs:
      endpoints: glusterfs-cluster
      path: users
      readOnly: false
  arguments:
    parameters:
    - name: samples
      value: "/k11e/pvdisk/fastbase/Users/wangjianshou/pipeline/shogun/samples"
    - name: outdir
      value: "/k11e/pvdisk/fastbase/Users/wangjianshou/pipeline/shogun/output/"
    - name: database
      value: "/k11e/pvdisk/fastbase/Users/wangjianshou/pipeline/shogun/"

  templates:
  - name: shogun-pipeline
    steps:
    - - name: step-generate-samples
        template: generate-samples
        arguments:
          parameters:
          - name: samples-file
            value: "{{workflow.parameters.samples}}"
    - - name: step-shogun
        template: shogun
        arguments:
          parameters:
          - name: sample
            value: "{{item.sample}}"
          - name: resultdir
            value: "{{item.resultdir}}"
        withParam: "{{steps.step-generate-samples.outputs.result}}"

  - name: generate-samples
    inputs:
      parameters:
      - name: samples-file
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        from os.path import basename
        with open("{{inputs.parameters.samples-file}}", "rt") as f:
          r = [{'sample':i.strip(), 'resultdir':basename(i.strip()).strip('.fa')} for i in f]
        json.dump(r, sys.stdout)
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 1Gi
      volumeMounts:
        - name: gluster-volumes-user
          mountPath: /k11e/pvdisk/fastbase/Users/

  - name: shogun
    inputs:
      parameters:
        - name: sample
        - name: resultdir
    script:
      image: wangjianshou/shogun_ubuntu_18.04:miniconda_4.5.11
      command: [sh]
      env:
        - name: LC_ALL
          value: C.UTF-8
        - name: LANG
          value: C.UTF-8
      source: |
        . /opt/miniconda/etc/profile.d/conda.sh
        conda activate shogun
        python -m unittest discover shogun
        shogun assign-taxonomy --no-capitalist -a burst -i {{inputs.parameters.sample}} -d {{workflow.parameters.database}} -o {{workflow.parameters.outdir}}/taxonomy
        shogun assign-taxonomy -a burst -i {{inputs.parameters.sample}} -d {{workflow.parameters.database}} -o {{workflow.parameters.outdir}}/taxonomy.capitalist
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      volumeMounts:
        - name: gluster-volumes-user
          mountPath: /k11e/pvdisk/fastbase/Users

